export const LINE_CHART_DATA = "LINE_CHART_DATA";
export const UPDATE_X_VALUE= "UPDATE_X_VALUE";
export const UPDATE_Y_VALUE = "UPDATE_Y_VALUE";
export const UPDATE_CHART_DATA = "UPDATE_CHART_DATA"
export const ADD_API_ERROR = "ADD_API_ERROR";
export const FETCH_API_ERROR = "FETCH_API_ERROR";
export const SVG_MARGIN= 40;
export const SVG_WIDTH= 600;
export const SVG_HEIGHT= 500;
export const FETCH_API_MSG = "Fetch API Call Failed";
export const POST_API_MSG = "POST API Call Failed";
